### PR TITLE
Update to match the Porter License

### LINKED ISSUE #45: Which license is the repository under?
I noticed that this repository has two licenses listed which I think was an accident from how the repo was created in GitHub. @MChorfa Did you intend to license this under the "unlicense" instead of the MIT license?

### PR DESCRIPTION
**Pull request by MChorfa**
close #45

### CODE REVIEW

**Comment by carolynvs** [comment]
Do you want to continue to have two license files in the repository (LICENSE and LICENSE.md)? Only one is necessary and the other may be deleted. Looks like github supports either.

**Comment by MChorfa** [comment]
Yep. Deleted the `MIT` one

**Comment by carolynvs** [comment]
I don't see LICENSE was deleted, so there are still two files that contain a license. I was suggesting that you delete LICENCE (without a file extension) so that we only have LICENSE.md

https://github.com/MChorfa/porter-helm3/tree/0a118085fcd2e33548df8f62a8a362f433683c71

**Review by carolynvs — APPROVED** [review]
Thanks for making the license more clear! 👍

**Pull request merged**
